"""
rank.py
Final step: combines all 6 Fit Score components, applies the behavioral
multiplier, drops honeypots, ranks the top 100, generates reasoning text,
and writes a submission CSV that exactly matches validate_submission.py's
requirements.

IMPORTANT: reasoning text is generated by template/rule, NOT by calling any
LLM API -- the competition rules explicitly forbid network access during the
ranking step (has_network_during_ranking: false in submission_metadata.yaml).
This must run fully offline.
"""

import argparse
import pandas as pd

from skill_depth_score import normalize, HIGH_TRUST_SKILLS

# Must sum to 1.0 -- see RUBRIC_v1.md for the reasoning behind each weight.
WEIGHTS = {
    "career_context_score": 0.35,
    "skill_depth_score": 0.25,
    "experience_score": 0.15,
    "tenure_stability_score": 0.10,
    "geo_eligibility_score": 0.08,
    "quality_score": 0.07,
}


def compute_fit_score(df: pd.DataFrame) -> pd.DataFrame:
    df["fit_score"] = sum(df[col] * w for col, w in WEIGHTS.items())
    df["final_score"] = df["fit_score"] * df["behavioral_multiplier"]
    return df


def top_matched_skills(skills: list, max_n: int = 3) -> list:
    """Names of the candidate's high-trust skills with real depth, for reasoning text."""
    out = []
    for s in skills:
        if normalize(s.get("name", "")) in HIGH_TRUST_SKILLS and s.get("proficiency") in (
            "advanced",
            "expert",
        ):
            out.append(s["name"])
    return out[:max_n]

#Changes made: keeps all the logic exactly as-is, just restructure how the parts join so experience and skills fold into sentence 1 rather than dangling as fragments.
def generate_reasoning(row) -> str:
    ccs = row["career_context_score"]

    # Sentence 1: career-context + experience + skills — one flowing sentence
    if ccs >= 0.5:
        main = (
            f"Career history at {row['current_company']} shows strong alignment "
            f"with the role's core requirements (career-context fit {ccs:.2f}), "
            f"with {row['years_of_experience']:.1f} years of experience"
        )
    elif ccs >= 0.35:
        main = (
            f"Career history shows moderate alignment with the role "
            f"(career-context fit {ccs:.2f}), "
            f"with {row['years_of_experience']:.1f} years of experience"
        )
    else:
        main = (
            f"Career history shows limited alignment with the role's core requirements "
            f"(career-context fit {ccs:.2f}), "
            f"with {row['years_of_experience']:.1f} years of experience"
        )

    # Attach skill info to close sentence 1
    matched = top_matched_skills(row["skills"])
    if matched:
        main += f" and real depth in {', '.join(matched)}."
    elif row["skill_depth_score"] > 0:
        main += ", with some relevant skills though limited depth."
    else:
        main += "; skill list shows no direct JD match."

    # Sentence 2: concerns only when they exist (tenure moved here too)
    concerns = []
    if row["tenure_stability_score"] <= 0.4:
        concerns.append("pattern of short tenures with climbing titles")
    if not row["open_to_work_flag"]:
        concerns.append("not currently open to work")
    if row["notice_period_days"] and row["notice_period_days"] > 90:
        concerns.append(f"{int(row['notice_period_days'])}-day notice period")
    if row["recruiter_response_rate"] is not None and row["recruiter_response_rate"] < 0.10:
        concerns.append("low recruiter response rate")
    if concerns:
        return main + " Note: " + ", ".join(concerns) + "."

    return main

def build_submission(df: pd.DataFrame) -> pd.DataFrame:
    # Stage 1: drop honeypots entirely
    df = df[~df["is_honeypot"]].copy()

    # Stage 2: combine into final score
    df = compute_fit_score(df)

    # Sort: final_score descending, tie-break candidate_id ascending
    # (validate_submission.py requires exactly this tie-break rule)
    df = df.sort_values(
        by=["final_score", "candidate_id"], ascending=[False, True]
    ).reset_index(drop=True)

    top100 = df.head(100).copy()
    top100["rank"] = range(1, 101)
    top100["score"] = top100["final_score"].round(6)
    top100["reasoning"] = top100.apply(generate_reasoning, axis=1)

    return top100[["candidate_id", "rank", "score", "reasoning"]]


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--checkpoint", default="candidates_with_all_scores.pkl")
    parser.add_argument("--out", default="azurewiz.csv")
    args = parser.parse_args()

    print(f"Loading checkpoint: {args.checkpoint}")
    df = pd.read_pickle(args.checkpoint)
    print(f"Loaded {len(df):,} candidates ({df['is_honeypot'].sum()} honeypots will be excluded)")

    submission = build_submission(df)

    submission.to_csv(args.out, index=False)
    print(f"\nSaved {len(submission)} ranked candidates to {args.out}")

    print("\nTop 5:")
    print(submission.head(5).to_string(index=False))

    print("\nBottom 5 (of the top 100):")
    print(submission.tail(5).to_string(index=False))

    print(f"\nScore range: {submission['score'].max():.4f} (rank 1) to {submission['score'].min():.4f} (rank 100)")
